# Taskfile.yml
version: '3'

vars:
  # 2-day delay (security verification window)
  EXCLUDE_NEWER_DAYS: 2
  EXCLUDE_NEWER_DATE:
    sh: date -u -d '{{.EXCLUDE_NEWER_DAYS}} days ago' '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || date -u -v-{{.EXCLUDE_NEWER_DAYS}}d '+%Y-%m-%dT%H:%M:%SZ'

tasks:
  uv:add:
    desc: "Add package (with {{.EXCLUDE_NEWER_DAYS}}-day delay)"
    cmds:
      - echo "Excluding packages newer than {{.EXCLUDE_NEWER_DATE}}"
      - uv add --exclude-newer {{.EXCLUDE_NEWER_DATE}} {{.CLI_ARGS}}

  uv:lock:
    desc: "Lock dependencies (with {{.EXCLUDE_NEWER_DAYS}}-day delay)"
    cmds:
      - echo "Excluding packages newer than {{.EXCLUDE_NEWER_DATE}}"
      - uv lock --exclude-newer {{.EXCLUDE_NEWER_DATE}}

  uv:lock:upgrade:
    desc: "Upgrade all dependencies (with {{.EXCLUDE_NEWER_DAYS}}-day delay)"
    cmds:
      - uv lock --upgrade --exclude-newer {{.EXCLUDE_NEWER_DATE}}

  uv:sync:
    desc: "Sync environment"
    cmds:
      - uv sync --frozen --all-groups

  uv:dev:
    desc: "Set up development environment"
    cmds:
      - task: uv:sync
      - uv run pre-commit install

  uv:run:
    desc: "Run command via uv with locked, time-delayed dependencies (e.g., task uv:run -- python app.py)"
    cmds:
      - uv run --no-sync {{.CLI_ARGS}}

  uv:security:
    desc: "Run security scan"
    cmds:
      - uv run pip-audit
      - trivy fs --severity HIGH,CRITICAL .
